version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      # Install Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      # - ./snyk config set api="$SNYK_AUTH_TOKEN"
      # Build Docker image for testing
      - echo Build client and backend docker images for testing...
      - docker build -t timotheedesurmont/client-test -f ./client/Dockerfile.dev ./client
      - docker build -t timotheedesurmont/server-test -f ./server/Dockerfile.dev ./server
      - docker build -t timotheedesurmont/worker-test -f ./worker/Dockerfile.dev ./worker
      - docker build -t timotheedesurmont/service_param-test -f ./service_param/Dockerfile.dev ./service_param
      - docker build -t timotheedesurmont/service_stock-test -f ./service_stock/Dockerfile.dev ./service_stock
  build:
    commands:
      - echo Build started on `date`
      # Run tests with built Docker images
      - echo Run client tests...
      - docker run -e CI=true timotheedesurmont/client-test
      - echo Run server tests...
      - docker run -e CI=true timotheedesurmont/server-test
      - echo Run worker tests...
      - docker run -e CI=true timotheedesurmont/worker-test
      - echo Run service_param tests...
      - docker run -e CI=true timotheedesurmont/service_param-test
      - echo Run service_stock tests...
      - docker run -e CI=true timotheedesurmont/service_stock-test
      # Scan Docker image with Snyk
      
      ## client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker timotheedesurmont/client-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker timotheedesurmont/client-test:latest --file=./client/Dockerfile.dev
      
      ## server
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker timotheedesurmont/server-test:latest --file=./server/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker timotheedesurmont/server-test:latest --file=./server/Dockerfile.dev

      ## worker
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker timotheedesurmont/worker-test:latest --file=./worker/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker timotheedesurmont/worker-test:latest --file=./worker/Dockerfile.dev
      
      ## service_param
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker timotheedesurmont/service_param-test:latest --file=./service_param/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker timotheedesurmont/service_param-test:latest --file=./service_param/Dockerfile.dev

      ## service_Stock
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker timotheedesurmont/service_stock-test:latest --file=./service_stock/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker timotheedesurmont/service_stock-test:latest --file=./service_stock/Dockerfile.dev
      
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t timotheedesurmont/wkf-client ./client
      - docker build -t timotheedesurmont/wkf-server ./server
      - docker build -t timotheedesurmont/wkf-worker ./worker
      - docker build -t timotheedesurmont/wkf-service_param ./service_param
      - docker build -t timotheedesurmont/wkf-service_stock ./service_stock
      - docker build -t timotheedesurmont/wkf-nginx ./nginx
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push timotheedesurmont/wkf-client
      - docker push timotheedesurmont/wkf-server
      - docker push timotheedesurmont/wkf-worker
      - docker push timotheedesurmont/wkf-service_param
      - docker push timotheedesurmont/wkf-service_stock
      - docker push timotheedesurmont/wkf-nginx