version: "3.3"
services:
  nginx:
    depends_on:
      - user
      - dropdown
      - update
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  user:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: user
    volumes:
      - /app/node_modules
      - "./user/src:/app/src"
    env_file:
      - ./env/backend.env
  dropdown:
    build:
      context: ./dropdown
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: dropdown
    volumes:
      - /app/node_modules
      - "./dropdown/src:/app/src"
    env_file: 
      - ./env/backend.env
  update:
    build:
      context: ./update
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: update
    volumes:
      - /app/node_modules
      - "./update/src:/app/src"
    env_file: 
      - ./env/backend.env