version: "3.3"
services:
  nginx:
    depends_on:
      - user
      - drop
      - param
      - stock
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  user:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: user
    volumes:
      - /app/node_modules
      - "./user/src:/app/src"
    env_file:
      - ./env/backend.env
  drop:
    build:
      context: ./drop
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: drop
    volumes:
      - /app/node_modules
      - "./drop/src:/app/src"
    env_file: 
      - ./env/backend.env
  param:
    build:
      context: ./param
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: param
    volumes:
      - /app/node_modules
      - "./param/src:/app/src"
    env_file: 
      - ./env/backend.env
  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: stock
    volumes:
      - /app/node_modules
      - "./stock/src:/app/src"
    env_file:
      - ./env/backend.env