version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - service_dropdown
      - service_param
      - service_search
      - service_stock
      - service_user
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./client/src:/app/src"
    env_file:
      - ./env/client.env
  service_dropdown:
    build:
      context: ./service_dropdown
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_dropdown/src:/app/src"
    env_file:
      - ./env/server.env
  service_param:
    build:
      context: ./service_param
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_param/src:/app/src"
    env_file:
      - ./env/server.env
  service_search:
    build:
      context: ./service_search
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_search/src:/app/src"
    env_file:
      - ./env/server.env
  service_stock:
    build:
      context: ./service_stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_stock/src:/app/src"
    env_file:
      - ./env/server.env
  service_user:
    build:
      context: ./service_user
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_user/src:/app/src"
    env_file:
      - ./env/server.env