version: "3.3"
services:
  nginx:
    depends_on:
      - server
      - param
      - stock
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules
      - "./server/src:/app/src"
    env_file:
      - ./env/backend.env
  param:
    build:
      context: ./param
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: param
    volumes:
      - /app/node_modules
      - "./param/src:/app/src"
    env_file: 
      - ./env/backend.env
  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: stock
    volumes:
      - /app/node_modules
      - "./stock/src:/app/src"
    env_file:
      - ./env/backend.env