version: "3.3"
services:
  nginx:
    depends_on:
      - user
      - dropdown
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  user:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: user
    volumes:
      - /app/node_modules
    env_file:
      - ./env/backend.env
  dropdown:
    build:
      context: ./dropdown
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: dropdown
    volumes:
      - /app/node_modules
    env_file: 
      - ./env/backend.env