version: "3.3"
services:
  nginx:
    depends_on:
      - service_users
      - client
      - dropdown
      - param
      - search
      - stock
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  service_users:
    build:
      context: ./service_users
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_users/src:/app/src"
    env_file:
      - ./env/server.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./client/src:/app/src"
    env_file:
      - ./env/client.env
  dropdown:
    build:
      context: ./dropdown
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./dropdown/src:/app/src"
    env_file:
      - ./env/server.env
  param:
    build:
      context: ./param
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./param/src:/app/src"
    env_file:
      - ./env/server.env    
  search:
    build:
      context: ./search
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./search/src:/app/src"
    env_file:
      - ./env/server.env
  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./stock/src:/app/src"
    env_file:
      - ./env/server.env