version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - server
      - worker
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./client/src:/app/src"
    env_file:
      - ./env/client.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./server/src:/app/src"
    env_file:
      - ./env/server.env
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./worker/src:/app/src"
    env_file:
      - ./env/server.env