version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - server
      - account
      - dropdown
      - param
      - stock
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    restart: on-failure
    container_name: client
    volumes:
      - /app/node_modules
      - "./client/src:/app/src"
    env_file:
      - ./env/client.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules
      - "./server/src:/app/src"
    env_file:
      - ./env/server.env
  account:
    build:
      context: ./account
      dockerfile: Dockerfile.dev
    expose:
      - "5000"
    ports:
      - "5000:5000" #nginx:container
    restart: on-failure
    container_name: account
    volumes:
      - /app/node_modules
      - "./account/src:/app/src"
    env_file:
      - ./env/server.env
    environment:
      - PORT=5000
  dropdown:
    build:
      context: ./dropdown
      dockerfile: Dockerfile.dev
    expose:
      - "5001"
    restart: on-failure
    # container_name: dropdown
    volumes:
      - /app/node_modules
      - "./dropdown/src:/app/src"
    env_file:
      - ./env/server.env
  param:
    build:
      context: ./param
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: param
    volumes:
      - /app/node_modules
      - "./param/src:/app/src"
    env_file: 
      - ./env/server.env
  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    container_name: stock
    volumes:
      - /app/node_modules
      - "./stock/src:/app/src"
    env_file:
      - ./env/server.env