version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - server
      # - service_dropdown
      - service_param
      - service_stock
      - worker_export
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./client/src:/app/src"
    env_file:
      - ./env/client.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./server/src:/app/src"
    env_file:
      - ./env/server.env
  # service_dropdown:
  #   build:
  #     context: ./service_dropdown
  #     dockerfile: Dockerfile.dev
  #   restart: on-failure
  #   volumes:
  #     - /app/node_modules
  #     - "./service_dropdown/src:/app/src"
  #   env_file:
  #     - ./env/server.env
  service_param:
    build:
      context: ./service_param
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_param/src:/app/src"
    env_file:
      - ./env/server.env
  service_stock:
    build:
      context: ./service_stock
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./service_stock/src:/app/src"
    env_file:
      - ./env/server.env
  worker_export:
    build:
      context: ./worker_export
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - "./worker_export/src:/app/src"
    env_file:
      - ./env/server.env